### PR TITLE
Swaschnick/make timeouts configurable and more parallelism

### LINKED ISSUE #33: Make Header in RestClient configurable and improve performance for many timed-out checks
- The PCP-Header is hardcoded in the restclient
- For many failing request eg. some VMs are not reachable the perfomance is under all pig

### PR DESCRIPTION
**Pull request by CanardSauvage**
fixes #33

### CODE REVIEW

File: dash-core/src/main/java/de/axelspringer/ideas/tools/dash/business/check/CheckService.java [hunk 1]
```diff
@@ -9,35 +10,44 @@
...
+
     @Autowired
     private List<CheckExecutor> checkExecutors;
 
-    @SuppressWarnings("unchecked")
+    private int numberOfParallelTask = 8;
+
     public List<CheckResult> check(List<Check> checks) {
+        try {
+            ForkJoinPool forkJoinPool = new ForkJoinPool(getNumberOfParallelTask());
```
Comment (CanardSauvage) [inline dash-core/src/main/java/de/axelspringer/ideas/tools/dash/business/check/CheckService.java]: unused getter?, why not property?

Comment (CanardSauvage) [inline dash-core/src/main/java/de/axelspringer/ideas/tools/dash/business/check/CheckService.java]: Now you can use this in your own dash with checkService.set to manually override the number of parallel checks

**Comment by CanardSauvage** [comment]
Was reviewed by gaffa
